### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by emetselchs** [Gorkycreator/obsidian-quick-tagger#9]
hi there! really interested in your plugin, but I'm having trouble with installing. I've unzipped the folder and copied it to my plugin folder, but I receive an error when trying to enable it. I also can't find main.js... sorry if this is a dumb question, I'm still new to obsidian :)

**Comment by Gorkycreator** [comment]
Thanks for your interest! Sounds like you're downloading the code from the master branch rather than the release page.

![image](https://github.com/Gorkycreator/obsidian-quick-tagger/assets/70078909/67ec3dca-aa06-45df-853d-2de33b9aacc0)

To manually install the plugin correctly, go to the latest release--which you can find [here](https://github.com/Gorkycreator/obsidian-quick-tagger/releases)--and download `main.js` and `manifest.json` from there, no zip file needed. When you've got everything in place, it should look like this (data.json will be created automatically when you enable the plugin and tweak the settings):

![image](https://github.com/Gorkycreator/obsidian-quick-tagger/assets/70078909/a184df53-d3df-4fd7-b2df-980b19336d8c)


If you still have trouble with manually installing it, [Obsidian BRAT](https://github.com/TfTHacker/obsidian42-brat) can install plugins that aren't in the community plugins list yet[^1]. If you need more info on this option, there should be plenty of help available on [Obsidian's forums](https://forum.obsidian.md/).

[^1]: Quick Tagger has been submitted and is awaiting approval 🤞

**Comment by emetselchs** [comment]
got it!! thank you so much!
